# Generated by Django 3.2.12 on 2022-05-02 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20220430_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='verified',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Unverified', 'Unverified')], default='Unverified', max_length=15, verbose_name='Transaction Verified'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='verified',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Unverified', 'Unverified')], default='Unverified', max_length=15, verbose_name='Transaction Verified'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='acc_no',
            field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999999999999)], verbose_name='NUBAN'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='recipients_acc_no',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='Recipients Account Number'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='recipients_route_no',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(9999999999999)], verbose_name='Recipients Routing Number'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='acc_no',
            field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(999999999999999999999)]),
        ),
    ]
