# Generated by Django 3.2.12 on 2022-05-02 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220502_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='pin',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Transfer PIN'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='recipients_acc_no',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(99999999999999999999)], verbose_name='Recipients Account Number'),
        ),
        migrations.AlterField(
            model_name='debit',
            name='recipients_route_no',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(99999999999999999999)], verbose_name='Recipients Routing Number'),
        ),
    ]
