# Generated by Django 3.2.12 on 2022-02-15 18:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0002_auto_20220215_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='USD', max_length=4, verbose_name='Currency Type')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('pin', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)])),
                ('acc_no', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('route_no', models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)])),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User Bank Account',
                'verbose_name_plural': 'Users Bank Account',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('image', stdimage.models.StdImageField(blank=True, upload_to='user/passport')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', localflavor.us.models.USPostalCodeField(max_length=2)),
                ('zipcode', localflavor.us.models.USZipCodeField(max_length=10)),
                ('ssn', localflavor.us.models.USSocialSecurityNumberField(max_length=11)),
                ('country', models.ForeignKey(blank=True, default='US', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries_plus.country')),
            ],
            options={
                'verbose_name': 'User Next Of Kin',
                'verbose_name_plural': 'Users Next Of Kin',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='transaction_complete',
            new_name='complete_transaction',
        ),
        migrations.RemoveField(
            model_name='user',
            name='acc_no',
        ),
        migrations.RemoveField(
            model_name='user',
            name='route_no',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
