# Generated by Django 3.2.12 on 2022-02-19 05:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220215_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='ssn',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='account',
            name='swift_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank Swift Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Pending', 'Pending'), ('Blocked', 'Blocked'), ('Unverified', 'Unverified')], default='Unverified', max_length=15, verbose_name='Account Verified'),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Account Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='USD', max_length=4, verbose_name='Currency Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Transfer PIN'),
        ),
        migrations.AlterField(
            model_name='account',
            name='route_no',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Routing Number'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Current Residential Address'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='user/passport', verbose_name='Upload Profile Photo'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='phone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Postal/Zip Code'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='commercial_information',
            field=models.BooleanField(default=True, help_text='These are information we collect for commercial purposes and are used for analysis as well as providing accurate data statistics of our services usage. You hereby consent to the use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='google_ads',
            field=models.BooleanField(default=True, help_text='These is an advertising and delivery network service, aimed solely to provide advert placements based on your browser information. permiting this allows us provide you with adverts directly on our site. Be ensured that this does not constitute any security risk to you. You hereby consent to the use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='identifiers',
            field=models.BooleanField(default=True, help_text='These are information we collect to prevent fraud, do analysis as well as utilize cloud services. They include Email address, device identifiers (User IDs, IP and Location). You hereby consent to the use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='internet_or_other_electronic_network_activity_information',
            field=models.BooleanField(default=True, help_text='These are information we collect regarding the user interactions within the website. With this information we can provide cloud services such as Content Delivery Networks for static/asset and media files. You hereby consent to the use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='personal_information',
            field=models.BooleanField(default=True, help_text='These are personal information we collect to provide quality and personalized services to you. They include (First Name, Last Name, Phone Number, Social Accounts, Addresses, Photo). You hereby consent to the use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='social_account_integration',
            field=models.BooleanField(default=True, help_text='Facebook, Instagram, Twitter, Google Plus, Linkedin, these providers are integrated into the website to ensure we have proper information to provide for our social influence and lead generation. We do not share these information for any other purpose other than statistical analysis. You hereby consent to the use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Current Residential Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='user/passport', verbose_name='Upload Profile Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Postal/Zip Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Checking Account', 'Checking Account'), ('Corporate Account', 'Corporate Account'), ('Savings Account', 'Savings Account'), ('Student Account', 'Student Account')], default='Checking Account', max_length=18, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='complete_transaction',
            field=models.BooleanField(default=True, verbose_name='Complete Transaction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Your Full Name'),
        ),
        migrations.CreateModel(
            name='VerificationDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('file', models.FileField(blank=True, null=True, upload_to='user/verify/docs', verbose_name='Upload Passport/Drivers License/SSN Card/NIN Card')),
                ('address_file', models.FileField(blank=True, null=True, upload_to='user/verify/docs', verbose_name='Upload Utility Bill')),
                ('company_certificate', models.FileField(blank=True, null=True, upload_to='user/verify/docs', verbose_name='Upload Company Certificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Verification Documents',
                'verbose_name_plural': 'Users Verification Documents',
                'ordering': ['-created'],
                'managed': True,
            },
        ),
    ]
