# Generated by Django 3.2.12 on 2022-04-30 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220219_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('YEN', 'YEN'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='USD', max_length=4, verbose_name='Currency Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Transfer PIN'),
        ),
        migrations.AlterField(
            model_name='account',
            name='route_no',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000000), django.core.validators.MaxValueValidator(999999999)], verbose_name='Routing Number'),
        ),
    ]
