# Generated by Django 3.2.12 on 2022-04-30 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220430_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='route_no',
        ),
        migrations.RemoveField(
            model_name='account',
            name='swift_code',
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Transfer PIN'),
        ),
    ]
