# Generated by Django 3.2.12 on 2022-04-30 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220430_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)], verbose_name='Account Number'),
        ),
    ]
