# Generated by Django 3.2.12 on 2022-05-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_account_acc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacy',
            name='commercial_information',
            field=models.BooleanField(default=True, help_text='These are information we collect for commercial purposes\n            and are used for analysis as well as providing accurate data statistics of our\n            services usage. You hereby consent to the use and transfer of your Personal Information\n             to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='cookies_and_tracking',
            field=models.BooleanField(default=True, help_text='This is a must have integration to enable us provide\n            you with proper services and security. They do not create any security bridge\n            for you and can only be used to login, signout and even ensure your\n             sessions are still working. You hereby consent to the use and transfer of your\n             Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='google_ads',
            field=models.BooleanField(default=True, help_text='These is an advertising and delivery network service,\n            aimed solely to provide advert placements based on your browser information.\n            permiting this allows us provide you with adverts directly on our site. Be ensured\n             that this does not constitute any security risk to you. You hereby consent to the\n             use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='identifiers',
            field=models.BooleanField(default=True, help_text='These are information we collect to prevent fraud, do\n            analysis as well as utilize cloud services. They include Email address, device\n            identifiers (User IDs, IP and Location). You hereby consent to the use and\n             transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='internet_or_other_electronic_network_activity_information',
            field=models.BooleanField(default=True, help_text='These are information we collect regarding the user\n            interactions within the website. With this information we can provide cloud services\n            such as Content Delivery Networks for static/asset and media files. You hereby consent\n             to the use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='personal_information',
            field=models.BooleanField(default=True, help_text='These are personal information we collect to provide\n            quality and personalized services to you. They include (First Name, Last Name,\n            Phone Number, Social Accounts, Addresses, Photo). You hereby consent to the\n             use and transfer of your Personal Information to countries outside the European Union.'),
        ),
        migrations.AlterField(
            model_name='privacy',
            name='social_account_integration',
            field=models.BooleanField(default=True, help_text='Facebook, Instagram, Twitter, Google Plus, Linkedin,\n             these providers are integrated into the website to ensure we have proper\n             information to provide for our social influence and lead generation. We do not share\n              these information for any other purpose other than statistical analysis. You hereby\n              consent to the use and transfer of your Personal Information to countries outside the European Union.'),
        ),
    ]
