# Generated by Django 3.2.12 on 2022-05-24 18:50

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_plus', '0005_auto_20160224_1804'),
        ('users', '0013_auto_20220502_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='120 mary lane', max_length=255, verbose_name='Current Residential Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, default='US', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='countries_plus.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='user/passport', verbose_name='Upload Profile Photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Postal/Zip Code'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Your Full Name'),
        ),
    ]
